#!/bin/bash
### Job Name
#PBS -N megahit_tower

### Project code
#PBS -q himem3
#PBS -j oe
#PBS -l select=1:ncpus=144
#PBS -o logs

cd $PBS_O_WORKDIR

module load megahit/1.2.9

FASTQ1="../data/tower/ground_D1_T3.R1.tr.fastq,../data/tower/ground_D1_T4.R1.tr.fastq,../data/tower/ground_D1_T5.R1.tr.fastq,../data/tower/ground_D1_T6.R1.tr.fastq,../data/tower/ground_D2_T1.R1.tr.fastq,../data/tower/ground_D2_T2.R1.tr.fastq,../data/tower/ground_D2_T3.R1.tr.fastq,../data/tower/ground_D2_T4.R1.tr.fastq,../data/tower/ground_D2_T5.R1.tr.fastq,../data/tower/ground_D2_T6.R1.tr.fastq,../data/tower/ground_D3_T1.R1.tr.fastq,../data/tower/ground_D3_T2.R1.tr.fastq,../data/tower/ground_D3_T3.R1.tr.fastq,../data/tower/ground_D3_T4.R1.tr.fastq,../data/tower/ground_D3_T5.R1.tr.fastq,../data/tower/ground_D3_T6.R1.tr.fastq,../data/tower/ground_D4_T1.R1.tr.fastq,../data/tower/ground_D4_T2.R1.tr.fastq,../data/tower/ground_D4_T3.R1.tr.fastq,../data/tower/ground_D4_T4.R1.tr.fastq,../data/tower/ground_D4_T5.R1.tr.fastq,../data/tower/ground_D4_T6.R1.tr.fastq,../data/tower/ground_D5_T1.R1.tr.fastq,../data/tower/ground_D5_T2.R1.tr.fastq,../data/tower/ground_D5_T3.R1.tr.fastq,../data/tower/ground_D5_T4.R1.tr.fastq,../data/tower/ground_D5_T5.R1.tr.fastq,../data/tower/ground_D5_T6.R1.tr.fastq,../data/tower/ground_D6_T1.R1.tr.fastq,../data/tower/ground_D6_T2.R1.tr.fastq,../data/tower/tower_D1_T3.R1.tr.fastq,../data/tower/tower_D1_T4.R1.tr.fastq,../data/tower/tower_D1_T5.R1.tr.fastq,../data/tower/tower_D1_T6.R1.tr.fastq,../data/tower/tower_D2_T1.R1.tr.fastq,../data/tower/tower_D2_T2.R1.tr.fastq,../data/tower/tower_D2_T3.R1.tr.fastq,../data/tower/tower_D2_T4.R1.tr.fastq,../data/tower/tower_D2_T5.R1.tr.fastq,../data/tower/tower_D2_T6.R1.tr.fastq,../data/tower/tower_D3_T1.R1.tr.fastq,../data/tower/tower_D3_T2.R1.tr.fastq,../data/tower/tower_D3_T3.R1.tr.fastq,../data/tower/tower_D3_T4.R1.tr.fastq,../data/tower/tower_D3_T5.R1.tr.fastq,../data/tower/tower_D3_T6.R1.tr.fastq,../data/tower/tower_D4_T1.R1.tr.fastq,../data/tower/tower_D4_T2.R1.tr.fastq,../data/tower/tower_D4_T3.R1.tr.fastq,../data/tower/tower_D4_T4.R1.tr.fastq,../data/tower/tower_D4_T5.R1.tr.fastq,../data/tower/tower_D4_T6.R1.tr.fastq,../data/tower/tower_D5_T1.R1.tr.fastq,../data/tower/tower_D5_T2.R1.tr.fastq,../data/tower/tower_D5_T3.R1.tr.fastq,../data/tower/tower_D5_T4.R1.tr.fastq,../data/tower/tower_D5_T5.R1.tr.fastq,../data/tower/tower_D5_T6.R1.tr.fastq,../data/tower/tower_D6_T1.R1.tr.fastq,../data/tower/tower_D6_T2.R1.tr.fastq"
FASTQ2="../data/tower/ground_D1_T3.R2.tr.fastq,../data/tower/ground_D1_T4.R2.tr.fastq,../data/tower/ground_D1_T5.R2.tr.fastq,../data/tower/ground_D1_T6.R2.tr.fastq,../data/tower/ground_D2_T1.R2.tr.fastq,../data/tower/ground_D2_T2.R2.tr.fastq,../data/tower/ground_D2_T3.R2.tr.fastq,../data/tower/ground_D2_T4.R2.tr.fastq,../data/tower/ground_D2_T5.R2.tr.fastq,../data/tower/ground_D2_T6.R2.tr.fastq,../data/tower/ground_D3_T1.R2.tr.fastq,../data/tower/ground_D3_T2.R2.tr.fastq,../data/tower/ground_D3_T3.R2.tr.fastq,../data/tower/ground_D3_T4.R2.tr.fastq,../data/tower/ground_D3_T5.R2.tr.fastq,../data/tower/ground_D3_T6.R2.tr.fastq,../data/tower/ground_D4_T1.R2.tr.fastq,../data/tower/ground_D4_T2.R2.tr.fastq,../data/tower/ground_D4_T3.R2.tr.fastq,../data/tower/ground_D4_T4.R2.tr.fastq,../data/tower/ground_D4_T5.R2.tr.fastq,../data/tower/ground_D4_T6.R2.tr.fastq,../data/tower/ground_D5_T1.R2.tr.fastq,../data/tower/ground_D5_T2.R2.tr.fastq,../data/tower/ground_D5_T3.R2.tr.fastq,../data/tower/ground_D5_T4.R2.tr.fastq,../data/tower/ground_D5_T5.R2.tr.fastq,../data/tower/ground_D5_T6.R2.tr.fastq,../data/tower/ground_D6_T1.R2.tr.fastq,../data/tower/ground_D6_T2.R2.tr.fastq,../data/tower/tower_D1_T3.R2.tr.fastq,../data/tower/tower_D1_T4.R2.tr.fastq,../data/tower/tower_D1_T5.R2.tr.fastq,../data/tower/tower_D1_T6.R2.tr.fastq,../data/tower/tower_D2_T1.R2.tr.fastq,../data/tower/tower_D2_T2.R2.tr.fastq,../data/tower/tower_D2_T3.R2.tr.fastq,../data/tower/tower_D2_T4.R2.tr.fastq,../data/tower/tower_D2_T5.R2.tr.fastq,../data/tower/tower_D2_T6.R2.tr.fastq,../data/tower/tower_D3_T1.R2.tr.fastq,../data/tower/tower_D3_T2.R2.tr.fastq,../data/tower/tower_D3_T3.R2.tr.fastq,../data/tower/tower_D3_T4.R2.tr.fastq,../data/tower/tower_D3_T5.R2.tr.fastq,../data/tower/tower_D3_T6.R2.tr.fastq,../data/tower/tower_D4_T1.R2.tr.fastq,../data/tower/tower_D4_T2.R2.tr.fastq,../data/tower/tower_D4_T3.R2.tr.fastq,../data/tower/tower_D4_T4.R2.tr.fastq,../data/tower/tower_D4_T5.R2.tr.fastq,../data/tower/tower_D4_T6.R2.tr.fastq,../data/tower/tower_D5_T1.R2.tr.fastq,../data/tower/tower_D5_T2.R2.tr.fastq,../data/tower/tower_D5_T3.R2.tr.fastq,../data/tower/tower_D5_T4.R2.tr.fastq,../data/tower/tower_D5_T5.R2.tr.fastq,../data/tower/tower_D5_T6.R2.tr.fastq,../data/tower/tower_D6_T1.R2.tr.fastq,../data/tower/tower_D6_T2.R2.tr.fastq"

megahit --presets meta-large -t 144 --tmp-dir ./tmp --min-contig-len 1000 --out-prefix tower_asm \
-1 $FASTQ1 -2 $FASTQ2 \
-o outdir_tower
